// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/**
 * Default [FirebaseOptions] for use with your Firebase apps.
 *
 * Example:
 * ```dart
 * import 'firebase_options.dart';
 * // ...
 * await Firebase.initializeApp(
 *   options: DefaultFirebaseOptions.currentPlatform,
 * );
 * ```
 */
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJEp3_jZ-TgfFrMoR1JYgG9o6l1SIcrQk',
    appId: '1:889199537687:android:3578cff1b656725e613652',
    messagingSenderId: '889199537687',
    projectId: 'safa-az-app',
    storageBucket: 'safa-az-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAgALsyTOssM_RCsW9Wn2uhjcNFihvp0o',
    appId: '1:889199537687:ios:6e94e58c07524aef613652',
    messagingSenderId: '889199537687',
    projectId: 'safa-az-app',
    storageBucket: 'safa-az-app.firebasestorage.app',
    iosBundleId: 'com.example.safaApp',
  );
}
